Added condition to make datatype a url
IN-CORE/incore-ui pull request #123
Opened 2023-07-19 19:36 UTC by Vismayak

I have only changed one file and though it was a simple change, I reformatted the file and moved the complex logic to another function in the same file

2023-07-19 21:09 UTC, longshuicy commented on src/components/children/NestedInfoTable.jsx
> +										<a href={`/semantics/api/types/${data[key]}`} target="_blank" rel="noopener noreferrer">{data[key]} </a>
1. can you put the `/semantics/api/types/` part in config?
2. Could you also restrict this to only incore: or ergo: ones? maybe use some regex?

2023-07-24 21:20 UTC, longshuicy requested changes

2023-07-24 21:20 UTC, longshuicy commented on src/components/children/NestedInfoTable.jsx
> +			console.log(`${config.hostname}semantics/api/types/` + "ergo");
could you remove the console.log

2023-07-24 21:20 UTC, longshuicy commented on src/app.config.js
> +config["semanticServiceType"] = `${hostname}/semantics/api/types`;
missing an ending "/" 
Or alternatively you can add that / when you do `${config.semanticServiceType}${data[key]}`

2023-07-24 21:20 UTC, longshuicy commented on src/components/children/NestedInfoTable.jsx
> +										rel="noopener noreferrer"
Maybe try the theme color #e8a114
<img width="485" alt="image" src="https://github.com/IN-CORE/incore-ui/assets/13950475/ed7cb5b7-5157-4bf1-a214-9ca0a216647c">
What do you think? up to you.

2023-07-25 14:42 UTC, longshuicy approved these changes

2023-07-26 18:29 UTC, ylyangtw approved these changes
looks good

2023-07-26 18:32 UTC, merged