170 Remodel INCORE home page
IN-CORE/incore-ui pull request #173
Opened 2024-01-10 16:19 UTC by Vismayak

Do you guys have any input on how I can make the page look better? :)

2024-01-17 19:43 UTC, longshuicy requested changes
- [ ] - Could you add a changelog entry?
- [ ] - Once expand I still see the logo overlapping the topbar. Could you check if you pushed your fix to that?
- [ ] <img width="795" alt="image" src="https://github.com/IN-CORE/incore-ui/assets/13950475/a2d08262-9b07-48d8-9121-d6553a09736c">
- [ ] - Could you unify the font? Either pick the same as the description; or the same as the instruction.
- [ ] - Could you double check all the buttons/links leads to a new tab so user can still stay on the same page
- [ ]  Since there are less content on the page now maybe we can increase the fontsize? thoughts?

2024-01-17 19:43 UTC, longshuicy commented on src/components/HomePage.jsx
> +										&nbsp;pyincore, a python package that contains service classes to connect with
"pyincore" is repeated here
<img width="290" alt="image" src="https://github.com/IN-CORE/incore-ui/assets/13950475/6717337f-6e33-47e5-8598-5e37d7db3303">

2024-01-17 19:43 UTC, longshuicy commented on src/components/HomePage.jsx
> +										className={classes.button}
new tab

2024-01-17 19:43 UTC, longshuicy commented on src/components/HomePage.jsx
> +										startIcon={<SchoolIcon />}
open in new tab

2024-01-17 19:43 UTC, longshuicy commented on src/components/HomePage.jsx
> +										style={{ marginRight: "1em" }}
You might want to remove the marginRight to be consistent with the space in between 2 buttons
<img width="295" alt="image" src="https://github.com/IN-CORE/incore-ui/assets/13950475/139c62b7-7ad8-4704-91bf-1ad40cef21ef">

2024-01-17 19:43 UTC, longshuicy commented on src/components/HomePage.jsx
> +										review our FAQs for the most common questions
I would put the hyperlink only around the "FAQs"

2024-01-17 19:43 UTC, longshuicy commented on src/components/HomePage.jsx
> +										join the IN-CORE Slack channel
Same only around the "IN-CORE slack channel"

2024-01-17 19:43 UTC, longshuicy commented on src/components/HomePage.jsx
> +									<Link href={`mailto:${config.mailingList}`} className={classes.link}>
Only around "email"?

2024-01-17 19:43 UTC, longshuicy commented on src/components/HomePage.jsx
> +								<Divider />
I would remove the last divider since it's the bottom of the screen. But up to you.

2024-01-31 21:41 UTC, Rashmil-1999 approved these changes
Looks good!

2024-02-01 16:39 UTC, longshuicy approved these changes

2024-02-01 16:39 UTC, merged